apiVersion: v1
appVersion: 23.3.0
description: GoCD is an open-source continuous delivery server to model and visualize
  complex workflows with ease.
home: https://www.gocd.org/
icon: https://gocd.github.io/assets/images/go-icon-black-192x192.png
keywords:
- gocd
- ci
- cd
- ci/cd
- continuous-integration
- continuous-delivery
- continuous-deployment
- continuous-testing
maintainers:
- email: chadw@thoughtworks.com
  name: chadlwilson
- email: arvind@thoughtworks.com
  name: arvindsv
name: gocd
sources:
- https://github.com/gocd/gocd
version: 2.3.1
